a = input('Digite algo: ')
print('O tipo primitivo desse valor é: ', type(a))
print('Tem espaço?', a.isspace())
print('É numero?', a.isnumeric())
print('É alfabetico?', a.isalpha())
print('É alfanumerico', a.isalnum())
